import { useContext, useEffect } from 'react'
import Head from 'next/head'
import { gql, GraphQLClient } from 'graphql-request'
import { PageContext } from '../components/context/pageContext'
import { HomeWrapper } from '../styles/basic.styles'
import { HeroSection } from '../components/hero'
import { MovieSection } from '../components/moviesSection'
import { FooterSection } from '../components/footer'
import { ToSlug } from '../components/animations/toSlug'
import { TopMenu } from '../components/menu/topbar'
import { LeftMenu } from '../components/menu/leftBar'

const Home = ({ videos, account }) => {
  const { isOpen, setIsOpen } = useContext(PageContext)

  // Reset the isOpen to remove the transition
  useEffect(() => {
    setIsOpen(false)
  }, [setIsOpen])

  // If 'watch' button is clicked, animate to slug-page with the <ToSlug />-animation
  const handleSlugTransition = (isOpen) => {
    if (isOpen == true) {
      return (
        <ToSlug />
      )
    }
  }

  return (
    <>
      {handleSlugTransition(isOpen)}

      <Head>
        <title>acme movies</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopMenu account={account} />
      <LeftMenu videos={videos} />
      <HomeWrapper >
        <HeroSection videos={videos} />
        <MovieSection videos={videos} />
        <FooterSection />
      </HomeWrapper>
    </>
  )
}

/** GET DATA **/
export const getStaticProps = async () => {
  const url = process.env.ENDPOINT
  // to communicate with the database (as in grapQL documentations)
  const graphQLClient = new GraphQLClient(url, {
    headers: {
      "Authorization": process.env.GRAPH_CMS_TOKEN
    }
  })

  // query to get the video-content
  const videosQuery = gql`
    query {
      videos{
        createdAt,
        id,
        title,
        subtitle,
        tag,
        description,
        myList,
        slug,
        displayTag,
        thumbnail{
          url
        },
        bigThumbnail{
          url
        }
        mp4{
          url
        }
      }
    }`

  // query to get the data regarding our only user
  const accountQuery = gql`
      query {
        account(where: {id:"cl266w77718si0cuq8nnqz05d"}){
          username
          avatar {
            url
          }
        }
      }`

  const data = await graphQLClient.request(videosQuery)
  const videos = data.videos
  const accountData = await graphQLClient.request(accountQuery)
  const account = accountData.account

  return {
    props: {
      videos,
      account
    }
  }
}

export default Home;